const mongoose = require('mongoose');

const ProfileSchema = new mongoose.Schema({
  userId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
  },
  fullName: {
    type: String,
    required: true,
  },
  bio: {
    type: String,
    required: false,
  },
  skills: {
    type: [String], // Array of user skills
    required: false,
  },
  tags: {
    type: [String], // Tags generated by AI
    default: [],
  },
  workIds: [
    {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Work', // Reference to the Work model
    },
  ],
  createdAt: {
    type: Date,
    default: Date.now,
  },
});

const Profile = mongoose.model('Profile', ProfileSchema);
module.exports = Profile;
